### ISSUE TITLE
Srila Prabhupada Pranam Mantra needs to be complete

### ISSUE THREAD

**Issue by meets2tarun** [byciitp/byciitp.github.io#1]
Hare Krishna, 
In temple program pdf, Prabhupada Pranam Mantra is incompete. It happened twice in the pdf

![image](https://user-images.githubusercontent.com/15213246/88454458-88db3780-ce8d-11ea-8c58-54ea5b1933b8.png)
@sheetal-g9

**Comment by sheetal-g9** [comment]
The issue is resolved in this commit : 
https://github.com/byciitp/byciitp.github.io/commit/cb9c931f786ba259dc68c17c4ad1f80a92092b1a
